name: VanishV2
<<<<<<< Updated upstream
main: superbobby\VanishV2\VanishV2
api: 4.12.1
extensions:
  Core: '>=7.4'
version: "3.2.0"
author: sqrrrrl
=======
main: sqrrl\VanishV2\VanishV2
api: 5.0.0
extensions:
  Core: '>=8.0'
version: "4.0.0"
author: sqrrl
>>>>>>> Stashed changes
commands:
  vanish:
    description: "Enter vanish mode"
    permission: "vanish.use"
    aliases:
    - v
permissions:
  vanish.use:
    description: "Permission to use the vanish command"
    default: op
  vanish.use.other:
    description: "Permission to vanish other player"
    default: op
  vanish.see:
     description: "Permission to see vanished players"
     default: op
  vanish.silent:
    description: "Permission to silently join the server"
    default: op
  vanish.attack:
    description: "allows you to attack players while vanished"
    default: op
