# VanishV2 Configuration
# Use the § symbol for color coding
# Color code list https://minecraft.tools/en/color-code.php

# Do not change this!
config-version: 9

# Messages Configuration
messages:
  # Messages for vanishing/unvanishing
  vanish-message: "§aYou are now vanished."
  unvanish-message: "§cYou are no longer vanished!"
  vanish-other: "§aVanished %name"
  unvanish-other: "§cUnvanished %name"
  vanished-other: "§aYou are now vanished."
  unvanished-other: "§cYou are no longer vanished!"
  
  # Messages for notifications
  vanish: "§7§o[%name: Vanished]"
  unvanish: "§7§o[%name: Unvanished]"
  
  # Fake join/leave messages
  FakeLeave-message: "§e%name left the game"
  FakeJoin-message: "§e%name joined the game"
  
  # Other messages
  hit-no-permission: "§cYou do not have permission to hit other players while vanished"
  hud-message: "§aYou are currently vanished"
  
  # Private message handling
  sender-error: "That player cannot be found"
  receiver-message: "§c%sender tried to send a message to you: §7%message"

# Vanish Modes Configuration
modes:
  default:
    name: "Default"
    description: "Standard vanish mode"
    permission: "vanish.mode.default"
    settings:
      fly: true
      night_vision: true
      disable_damage: true
      silent_chest: true
      hunger: false
  
  staff:
    name: "Staff"
    description: "Staff vanish mode with special features"
    permission: "vanish.mode.staff"
    settings:
      fly: true
      night_vision: true
      disable_damage: true
      silent_chest: true
      hunger: false
      staff_chat: true
      see_reports: true
  
  spectator:
    name: "Spectator"
    description: "Spectator mode with no interaction"
    permission: "vanish.mode.spectator"
    settings:
      fly: true
      night_vision: true
      disable_damage: true
      silent_chest: true
      hunger: false
      no_interact: true
      no_place: true
      no_break: true

# Vanish Groups Configuration
groups:
  default:
    name: "Default"
    description: "Standard vanish group"
    permission: "vanish.group.default"
    visible_to: ["default", "admin", "mod"]
    settings: {}
  
  admin:
    name: "Admin"
    description: "Admin vanish group"
    permission: "vanish.group.admin"
    visible_to: ["admin"]
    settings: {}
  
  mod:
    name: "Moderator"
    description: "Moderator vanish group"
    permission: "vanish.group.mod"
    visible_to: ["admin", "mod"]
    settings: {}

# Feature Settings
settings:
  # Join/Leave Messages
  enable-leave: false
  enable-join: false
  
  # Vanish Behavior
  unvanish-after-leaving: false
  unvanish-after-restart: false
  enable-fly: true
  disable-damage: true
  silent-chest: true
  hunger: false
  night-vision: true
  
  # Auto-Vanish
  auto-vanish:
    enabled: false
    default-mode: "default"
    default-group: "default"
    permissions:
      admin: "vanish.auto.admin"
      mod: "vanish.auto.mod"
  
  # Notification Settings
  notifications:
    notify-staff: true
    notify-join: true
    notify-leave: true
    notify-mode-change: true
    notify-group-change: true
  
  # Logging Settings
  logging:
    enabled: true
    max-logs: 1000
    log-vanish: true
    log-unvanish: true
    log-mode-change: true
    log-group-change: true
  
  # Stats Settings
  stats:
    enabled: true
    track-time: true
    track-modes: true
    track-groups: true

# Silent Join/Leave Settings
silent-join-leave:
  join: true
  leave: true
  vanished-only: true

# Private Message Settings
can-send-msg: false

# Additional Commands to Block When Vanished
additional-commands:
  # Example
  # tpa:
  #   sender-error: "That player cannot be found"
  #   receiver-message: "§c%sender tried to send a tp request to you"
